"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-15 16:19:01.048373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_code')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('task_icon','reward_image','proof','avatar')", name='ck_media_kind'),
    sa.CheckConstraint('size_bytes <= 5242880', name='ck_media_size'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    # FK media.uploaded_by -> users.id được thêm sau khi tạo bảng users (do cycle media<->users).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('avatar_media_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male','female')", name='ck_users_gender'),
    sa.CheckConstraint("role IN ('parent','child')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_family_role', 'users', ['family_id', 'role'], unique=False)
    # Bổ sung FK chéo media.uploaded_by -> users.id sau khi cả hai bảng đã tồn tại.
    op.create_foreign_key('media_uploaded_by_fkey', 'media', 'users', ['uploaded_by'], ['id'])
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_family_created', 'audit_log', ['family_id', 'created_at'], unique=False)
    op.create_table('game_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='waiting', nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('host_side', sa.String(length=6), nullable=False),
    sa.Column('guest_side', sa.String(length=6), nullable=True),
    sa.Column('turn_user_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('win_line', sa.JSON(), nullable=True),
    sa.Column('pending_offer', sa.String(length=10), nullable=True),
    sa.Column('pending_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("game_type IN ('caro','chess')", name='ck_game_type'),
    sa.CheckConstraint("pending_offer IS NULL OR pending_offer IN ('draw','takeback')", name='ck_game_pending_offer'),
    sa.CheckConstraint("result IS NULL OR result IN ('host_win','guest_win','draw')", name='ck_game_result'),
    sa.CheckConstraint("status IN ('waiting','active','finished','abandoned')", name='ck_game_status'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pending_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['turn_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_family_status', 'game_matches', ['family_id', 'status'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.Column('image_media_id', sa.UUID(), nullable=True),
    sa.Column('icon_emoji', sa.String(length=16), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_points > 0', name='ck_rewards_points'),
    sa.CheckConstraint('stock IS NULL OR stock >= 0', name='ck_rewards_stock'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['image_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rewards_family_active', 'rewards', ['family_id', 'is_active'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('icon_media_id', sa.UUID(), nullable=True),
    sa.Column('icon_emoji', sa.String(length=16), nullable=True),
    sa.Column('recurrence', sa.String(length=10), server_default='once', nullable=False),
    sa.Column('require_proof', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recurrence IN ('once','daily','weekly')", name='ck_tasks_recurrence'),
    sa.CheckConstraint('points > 0', name='ck_tasks_points'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['icon_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_family_active', 'tasks', ['family_id', 'is_active'], unique=False)
    op.create_table('weekly_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bonus_points > 0', name='ck_weekly_goal_bonus'),
    sa.CheckConstraint('target_count > 0', name='ck_weekly_goal_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', name='uq_weekly_goal_family')
    )
    op.create_table('game_moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('by_user_id', sa.UUID(), nullable=False),
    sa.Column('move', sa.Text(), nullable=False),
    sa.Column('resulting_fen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['game_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'ply', name='uq_gamemove_ply')
    )
    op.create_table('reward_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('requested','approved','rejected','cancelled')", name='ck_redemption_status'),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proof_media_id', sa.UUID(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress','submitted','approved','rejected')", name='ck_assignment_status'),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['proof_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_child_status', 'task_assignments', ['child_id', 'status'], unique=False)
    op.create_index('ix_assignments_family_status', 'task_assignments', ['family_id', 'status'], unique=False)
    op.create_table('weekly_bonus_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['weekly_goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'week_start', name='uq_weekly_bonus_child_week')
    )
    op.create_table('points_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('task_assignment_id', sa.UUID(), nullable=True),
    sa.Column('reward_redemption_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('task_approved','reward_redeemed','manual_adjust','weekly_bonus')", name='ck_ledger_kind'),
    sa.CheckConstraint('delta <> 0', name='ck_ledger_delta'),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['reward_redemption_id'], ['reward_redemptions.id'], ),
    sa.ForeignKeyConstraint(['task_assignment_id'], ['task_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_child_created', 'points_ledger', ['child_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # DDL Postgres-only (partial unique index + trigger append-only), khớp app/models/ddl.py.
    op.execute(
        """
CREATE UNIQUE INDEX IF NOT EXISTS uq_ledger_task_approved
    ON points_ledger (task_assignment_id) WHERE kind = 'task_approved';

CREATE UNIQUE INDEX IF NOT EXISTS uq_ledger_reward_redeemed
    ON points_ledger (reward_redemption_id) WHERE kind = 'reward_redeemed';

CREATE UNIQUE INDEX IF NOT EXISTS uq_assignment_active
    ON task_assignments (task_id, child_id)
    WHERE status IN ('in_progress', 'submitted');

CREATE UNIQUE INDEX IF NOT EXISTS uq_redemption_requested
    ON reward_redemptions (reward_id, child_id) WHERE status = 'requested';

CREATE UNIQUE INDEX IF NOT EXISTS uq_child_display_name
    ON users (family_id, lower(display_name)) WHERE role = 'child';

CREATE OR REPLACE FUNCTION prevent_ledger_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'points_ledger is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_points_ledger_append_only ON points_ledger;
CREATE TRIGGER trg_points_ledger_append_only
    BEFORE UPDATE OR DELETE ON points_ledger
    FOR EACH ROW EXECUTE FUNCTION prevent_ledger_mutation();
"""
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Trigger bị xoá theo bảng points_ledger; xoá luôn function đi kèm.
    op.execute("DROP FUNCTION IF EXISTS prevent_ledger_mutation() CASCADE")
    op.drop_index('ix_ledger_child_created', table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_table('weekly_bonus_awards')
    op.drop_index('ix_assignments_family_status', table_name='task_assignments')
    op.drop_index('ix_assignments_child_status', table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_table('reward_redemptions')
    op.drop_table('game_moves')
    op.drop_table('weekly_goals')
    op.drop_index('ix_tasks_family_active', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_rewards_family_active', table_name='rewards')
    op.drop_table('rewards')
    op.drop_index('ix_games_family_status', table_name='game_matches')
    op.drop_table('game_matches')
    op.drop_index('ix_audit_family_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_family_role', table_name='users')
    op.drop_table('users')
    op.drop_table('media')
    op.drop_table('families')
    # ### end Alembic commands ###
